# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    binary: scriptcheck
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: SmarTTYs
    name: scriptcheck
  footer: |
    ## Docker images
    
    - `ghcr.io/smarttys/{{ .ProjectName }}:latest`
    - `ghcr.io/smarttys/{{ .ProjectName }}:{{ .RawVersion }}`

snapshot:
  version_template: "{{ .Tag }}-dev"

# - "--label=org.opencontainers.image.description=ExampleDescription"
# - "--label=org.opencontainers.image.title={{ .ProjectName }}"
# - "--label=org.opencontainers.image.created={{.Date}}"
# - "--label=org.opencontainers.image.name={{.ProjectName}}"
# - "--label=org.opencontainers.image.revision={{.FullCommit}}"
# - "--label=org.opencontainers.image.version={{.Version}}"
# - "--label=org.opencontainers.image.source=https://github.com/SmarTTYs/{{ .ProjectName }}"  # {{.GitURL}}
# - "--label=org.opencontainers.image.url=https://github.com/SmarTTYs/{{ .ProjectName }}"
# - "--label=org.opencontainers.image.licenses=MIT"

dockers:
  - use: buildx
    goarch: arm64
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
      - "--provenance=false"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/SmarTTYs/{{ .ProjectName }}"
      - "--label=org.opencontainers.image.url=https://github.com/SmarTTYs/{{ .ProjectName }}"
      - "--label=org.opencontainers.image.description=CLI for extracting or validating ci pipeline scripts"
    image_templates:
      - &arm-latest-image "ghcr.io/smarttys/{{ .ProjectName }}:latest-arm64"
      - &arm-image "ghcr.io/smarttys/{{ .ProjectName }}:{{ .RawVersion }}-arm64"

  - use: buildx
    goarch: amd64
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--provenance=false"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/SmarTTYs/{{ .ProjectName }}"
      - "--label=org.opencontainers.image.url=https://github.com/SmarTTYs/{{ .ProjectName }}"
      - "--label=org.opencontainers.image.description=CLI for extracting or validating ci pipeline scripts"
    image_templates:
      - &amd-latest-image "ghcr.io/smarttys/{{ .ProjectName }}:latest-amd64"
      - &amd-image "ghcr.io/smarttys/{{ .ProjectName }}:{{ .RawVersion }}-amd64"

docker_manifests:
  - name_template: "ghcr.io/smarttys/scriptcheck:latest"
    image_templates:
      - *amd-latest-image
      - *arm-latest-image

  - name_template: "ghcr.io/smarttys/{{ .ProjectName }}:{{ .RawVersion }}"
    image_templates:
      - *amd-image
      - *arm-image
